# Support Vector Machine


In [1]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC

In [2]:
# load the iris datasets
from sklearn import svm, datasets
dataset = datasets.load_iris()

In [3]:
# fit a SVM model to the data
model = svm.SVC(kernel='rbf', C=0.01)
model.fit(dataset.data, dataset.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [4]:
# make predictions
expected = dataset.target
predicted = model.predict(dataset.data)

In [5]:
from sklearn import metrics
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.90      0.94      0.92        50
           2       0.94      0.90      0.92        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150

[[50  0  0]
 [ 0 47  3]
 [ 0  5 45]]


# Tunning Parameters 

In [10]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
# import some data to play with
iris = datasets.load_iris()

In [12]:
X = iris.data[:, :2] # we only take the first two features.
y = iris.target

In [13]:
def MySVMClassifier( my_kernel, my_C, my_gamma):
    
    svc = svm.SVC(kernel=my_kernel, C=my_C,gamma=my_gamma)
    svc.fit(X, y)
    
    h=0.02
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),np.arange(y_min, y_max, h))
 
    plt.subplot(1, 1, 1)
    Z = svc.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, cmap=plt.cm.Paired, alpha=0.8)
    plt.scatter(X[:, 0], X[:, 1], c=y)
    plt.xlabel('Sepal length')
    plt.ylabel('Sepal width')
    plt.xlim(xx.min(), xx.max())
    plt.show() 
    

In [14]:
from IPython.html import widgets
from IPython.html.widgets import interact

In [11]:
i = interact(MySVMClassifier, my_kernel=('linear','rbf'),my_C=(1,100), my_gamma=(1,100))

ValueError: ('linear', 'rbf') cannot be transformed to a widget